# Generated by Django 5.0.4 on 2024-05-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_file_encrypted_file_alter_file_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plainfile', models.FileField(upload_to='plainfiles/')),
                ('keyfile', models.FileField(blank=True, null=True, upload_to='keys/')),
                ('encryptedfile', models.FileField(blank=True, null=True, upload_to='encryptedfiles/')),
                ('decryptedfile', models.FileField(blank=True, null=True, upload_to='decryptedfiles/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
