# Generated by Django 5.0.4 on 2024-08-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_uploadedfile_delete_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='large_part',
            field=models.FileField(blank=True, null=True, upload_to='largeparts/'),
        ),
    ]
